Repository LittleProxy/LittleProxy, pull requests merged in 2022-05, with the labels that each got.

#104 run tests with GitHub actions
  .github/workflows/main.yml
  pom.xml
Labels: enhancement

#106 update dependencies
  pom.xml
  src/test/java/org/littleshoot/proxy/extras/SelfSignedMitmManagerTest.java
Labels: dependencies

#26 TLS 1.3 handshake bugfix
  .travis.yml
  README.md
  pom.xml
  src/main/java/org/littleshoot/proxy/impl/ProxyToServerConnection.java
  src/test/java/org/littleshoot/proxy/IdleTest.java
Labels: bug

#107 ignore tests only on MacOS and still run on Linux
  pom.xml
  src/test/java/org/littleshoot/proxy/BaseChainedProxyTest.java
  src/test/java/org/littleshoot/proxy/EncryptedUDTChainedProxyTest.java
  src/test/java/org/littleshoot/proxy/IdleTest.java
  src/test/java/org/littleshoot/proxy/MitmWithEncryptedUDTChainedProxyTest.java
  src/test/java/org/littleshoot/proxy/MitmWithUnencryptedUDTChainedProxyTest.java
  src/test/java/org/littleshoot/proxy/TestUtils.java
  src/test/java/org/littleshoot/proxy/UnencryptedUDTChainedProxyTest.java
Labels: enhancement

#111 Refactoring/cleanup
  README.md
  src/main/java/org/littleshoot/proxy/extras/ProxyProtocolMessage.java
  src/main/java/org/littleshoot/proxy/impl/CategorizedThreadFactory.java
  src/main/java/org/littleshoot/proxy/impl/ClientToProxyConnection.java
  src/main/java/org/littleshoot/proxy/impl/ConnectionFlow.java
  src/main/java/org/littleshoot/proxy/impl/DefaultHttpProxyServer.java
  src/main/java/org/littleshoot/proxy/impl/ProxyConnection.java
  src/main/java/org/littleshoot/proxy/impl/ProxyConnectionLogger.java
  src/main/java/org/littleshoot/proxy/impl/ProxyToServerConnection.java
  src/main/java/org/littleshoot/proxy/impl/ProxyUtils.java
  src/test/java/org/littleshoot/proxy/AbstractProxyTest.java
  src/test/java/org/littleshoot/proxy/BaseChainedProxyTest.java
  src/test/java/org/littleshoot/proxy/ChainedProxyWithFallbackTest.java
  src/test/java/org/littleshoot/proxy/DirectRequestTest.java
  src/test/java/org/littleshoot/proxy/EndToEndStoppingTest.java
  src/test/java/org/littleshoot/proxy/HttpFilterTest.java
  src/test/java/org/littleshoot/proxy/HttpStreamingFilterTest.java
  src/test/java/org/littleshoot/proxy/IdleTest.java
  src/test/java/org/littleshoot/proxy/KeepAliveTest.java
  src/test/java/org/littleshoot/proxy/MessageTerminationTest.java
  src/test/java/org/littleshoot/proxy/MitmProxyTest.java
  src/test/java/org/littleshoot/proxy/MitmWithChainedProxyTest.java
  src/test/java/org/littleshoot/proxy/ProxyHeadersTest.java
  src/test/java/org/littleshoot/proxy/ResponseInfo.java
  src/test/java/org/littleshoot/proxy/ThrottlingTest.java
  src/test/java/org/littleshoot/proxy/TimeoutTest.java
  src/test/java/org/littleshoot/proxy/VariableSpeedClientServerTest.java
  src/test/java/org/littleshoot/proxy/haproxy/ProxyProtocolClientHandler.java
  src/test/java/org/littleshoot/proxy/haproxy/ProxyProtocolHeader.java
  src/test/java/org/littleshoot/proxy/impl/ProxyUtilsTest.java
  src/test/java/org/littleshoot/proxy/test/HttpClientUtil.java
  src/test/java/org/littleshoot/proxy/test/SocketClientUtil.java
  src/test/java/org/littleshoot/proxy/websockets/WebSocketClient.java
  src/test/java/org/littleshoot/proxy/websockets/WebSocketServer.java
Labels: enhancement

#116 #115 reverted to maven-shade-plugin 3.2.4
  README.md
  RELEASE_NOTES.md
  pom.xml
Labels: bug, dependencies
